### ISSUE TITLE
Timeout attempting to use usbreplay.py

### ISSUE THREAD

**Issue by martinling** [wcooley/usbrevue#1]
I am attempting to use usbrevue on Ubuntu 12.10 to help me reverse engineer an RFID reader device.

I can capture packets and use the usbview and usbgraph programs, but any attempt to replay any packets results in the following crash. Any ideas?

$ sudo usbreplay.py --vid 0x1071 --pid 0x0001 < paxton-filtered.pcap  
In Replayer.set_interface: [Errno None] Unknown error 
Error trying to set alternate interface setting to 0
Error occured in replayer run loop. Here's the traceback
Traceback (most recent call last):
  File "/usr/local/bin/usbreplay.py", line 295, in run
    self.send_usb_packet(packet)
  File "/usr/local/bin/usbreplay.py", line 319, in send_usb_packet
    self.send_setup_packet(packet)
  File "/usr/local/bin/usbreplay.py", line 352, in send_setup_packet
    self.ctrl_transfer_from_device(packet)
  File "/usr/local/bin/usbreplay.py", line 376, in ctrl_transfer_from_device
    ret_array = self.device.ctrl_transfer(packet.setup.bmRequestType, packet.setup.bRequest, packet.setup.wValue, packet.setup.wIndex, packet.setup.wLength)
  File "/usr/local/lib/python2.7/dist-packages/pyusb-1.0.0a3-py2.7.egg/usb/core.py", line 702, in ctrl_transfer
    self.__get_timeout(timeout)
  File "/usr/local/lib/python2.7/dist-packages/pyusb-1.0.0a3-py2.7.egg/usb/backend/libusb1.py", line 596, in ctrl_transfer
    timeout))
  File "/usr/local/lib/python2.7/dist-packages/pyusb-1.0.0a3-py2.7.egg/usb/backend/libusb1.py", line 403, in _check
    raise USBError(_str_error[ret], ret, _libusb_errno[ret])
USBError: [Errno 32] Pipe error
[Errno 110] Operation timed out

**Comment by wcooley** [comment]
Oh boy, I am not sure. Here are a few suggestions:
- You might try the keyboard LED blinking demo, just to see if it works at all.
- Based on the release dates for pyusb on sourceforge, we must have been using 1.0.0-alpha-0; you might try that version in a virtualenv.
- The replayer was mostly Joanne's work and perhaps the most dubious of all of the pieces, due to the nature of the task. You might try sending e-mail to her; the one in the copyright is the last I have. We were originally hosting this in Bitbucket with Mercurial; you might try to contact her through her Bitbucket page (although that seems even less likely than the listed gmail address): https://bitbucket.org/jmcbride

This was the project for out capstone course and unfortunately it's been too far outside of my daily work to get any attention.
